"""Approval domain types (spec §8).

Spec §8 requires the approval UI to display four specific facts: the action, the
exact amount, the triggering condition, and the downside. `ApprovalRequest`
carries all four as structured fields.

That structure is a safety property, not tidiness. Capabilities read untrusted
external content (§13 Step 5 includes news analysis) and a Manager synthesizes
those results into decisions. If the amount an operator approves were prose
regenerated by a model, attacker-influenced text would sit between the decision
and the human authorising money. The numbers are data; §12.5's plain language is
rendered from them.
"""

from __future__ import annotations

from decimal import Decimal
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from jarvis.kernel.ids import BusinessId


class ApprovalState(StrEnum):
    """Lifecycle of one approval request.

    `EXPIRED_PAUSED` exists because spec §9 requires an unresolved approval to
    auto-pause the dependent workflow after 7 days and explicitly never
    auto-approve. Expiry is therefore a distinct outcome, not a silent yes.
    """

    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    EXPIRED_PAUSED = "expired_paused"


TERMINAL_STATES = frozenset(
    {ApprovalState.APPROVED, ApprovalState.DENIED, ApprovalState.EXPIRED_PAUSED}
)

OPERATOR_LABELS: dict[ApprovalState, str] = {
    ApprovalState.PENDING: "Needs your OK",
    ApprovalState.APPROVED: "You approved this",
    ApprovalState.DENIED: "You said no",
    ApprovalState.EXPIRED_PAUSED: "Timed out — company paused",
}
"""Operator-facing wording (spec §12.5). The only strings the UI may show."""


class ApprovalRequest(BaseModel):
    """A request for human approval of one action (spec §8)."""

    model_config = ConfigDict(frozen=True)

    approval_id: str
    business_id: BusinessId
    action_type: str
    state: ApprovalState = ApprovalState.PENDING

    action_summary: str = Field(min_length=1)
    """What will happen, in plain language. One sentence."""

    amount_usd: Decimal | None = None
    """Exact amount (spec §8). Required for any capital-moving action."""

    counterparty: str | None = None
    triggering_condition: str = Field(min_length=1)
    """Why this is being asked now (spec §8)."""

    downside: str = Field(min_length=1)
    """What could go wrong, in plain terms (spec §8)."""

    parameters: dict[str, object] = Field(default_factory=dict)
    decision_ref: str | None = None
    """Decision Log entry carrying the fuller "why" (spec §11.5, §12.5)."""

    @property
    def involves_capital(self) -> bool:
        """Return whether this action moves real money.

        Capital actions are never eligible for autonomy graduation in v1
        (spec §8, hard constraint).
        """
        return self.amount_usd is not None
